export const ADD_CONNECTION_RESPONSE = {
  status_code: 200,
  status: 'OK',
  data: {
    id: 'crm+activecampaign',
    name: 'ActiveCampaign',
    tag_line:
      'Integrated email marketing, marketing automation, and small business CRM. Save time while growing your business with sales automation.',
    icon: 'https://res.cloudinary.com/apideck/image/upload/v1529455970/catalog/activecampaign/icon128x128.png',
    logo: 'https://www.activecampaign.com/site/assets/social-2x.png',
    website: 'https://www.activecampaign.com/',
    unified_api: 'crm',
    service_id: 'activecampaign',
    auth_type: 'apiKey',
    form_fields: [
      {
        id: 'base_url',
        label: 'Base URL',
        value: '',
        placeholder: '',
        mask: false,
        type: 'text',
        required: true,
        description:
          'Provide your full API url. It can be found in your account on the My Settings page under the "Developer" tab. Generally, the URL will be in the form https://<your-account>.api-us1.com. The API is accessed using a base URL that is specific to your account.',
        disabled: false,
        custom_field: false,
        hidden: false,
        sensitive: false,
      },
      {
        id: 'api_key',
        label: 'API Key',
        value: '',
        placeholder: '',
        mask: false,
        type: 'text',
        required: true,
        description: '',
        disabled: false,
        custom_field: false,
        hidden: false,
        sensitive: true,
      },
    ],
    configurable_resources: ['opportunities', 'pipelines'],
    resource_schema_support: [],
    resource_settings_support: ['opportunities', 'pipelines'],
    settings_required_for_authorization: [],
    state: 'authorized',
    enabled: true,
    authorize_url: null,
    revoke_url: null,
  },
};
