export const ADDED_CONNECTIONS_RESPONSE = {
  status_code: 200,
  status: 'OK',
  data: [
    {
      id: 'crm+activecampaign',
      name: 'ActiveCampaign',
      tag_line:
        'Integrated email marketing, marketing automation, and small business CRM. Save time while growing your business with sales automation.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529455970/catalog/activecampaign/icon128x128.png',
      logo: 'https://www.activecampaign.com/site/assets/social-2x.png',
      website: 'https://www.activecampaign.com/',
      unified_api: 'crm',
      service_id: 'activecampaign',
      auth_type: 'apiKey',
      custom_mappings: [],
      form_fields: [
        {
          id: 'base_url',
          label: 'Base URL',
          value: 'https://apideck1600217394.api-us1.com',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description:
            'Provide your full API url. It can be found in your account on the My Settings page under the "Developer" tab. Generally, the URL will be in the form https://<your-account>.api-us1.com. The API is accessed using a base URL that is specific to your account.',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
        {
          id: 'api_key',
          label: 'API Key',
          value:
            'a1ffa05a296f99780689a6ebd44b7c966e5591ee13cd38e5116c26e22104ac1bfaa9e00a',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: true,
        },
      ],
      configuration: [
        {
          defaults: [
            {
              value: 123,
              id: 'monetary_amount',
              target: 'resource',
            },
            {
              value: 'AFN',
              id: 'currency',
              target: 'resource',
            },
            {
              value: '2',
              id: 'owner_id',
              target: 'resource',
            },
            {
              value: '2',
              id: 'pipeline_id',
              target: 'resource',
            },
            {
              value: '6',
              id: 'pipeline_stage_id',
              target: 'resource',
            },
          ],
          resource: 'opportunities',
        },
        {
          defaults: [
            {
              value: 'AFN',
              id: 'currency',
              target: 'resource',
            },
          ],
          resource: 'pipelines',
        },
      ],
      configurable_resources: ['opportunities', 'pipelines'],
      resource_schema_support: [],
      resource_settings_support: ['opportunities', 'pipelines'],
      settings_required_for_authorization: [],
      state: 'callable',
      integration_state: 'configured',
      enabled: true,
      settings: {
        base_url: 'https://apideck1600217394.api-us1.com',
      },
      metadata: {},
      created_at: 1644832920725,
      updated_at: 1644832968206,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'lead+activecampaign',
      name: 'ActiveCampaign',
      tag_line:
        'Integrated email marketing, marketing automation, and small business CRM. Save time while growing your business with sales automation.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529455970/catalog/activecampaign/icon128x128.png',
      logo: 'https://www.activecampaign.com/site/assets/social-2x.png',
      website: 'https://www.activecampaign.com/',
      unified_api: 'lead',
      service_id: 'activecampaign',
      auth_type: 'apiKey',
      custom_mappings: [],
      form_fields: [
        {
          id: 'base_url',
          label: 'Base URL',
          value: 'https://apideck1600217394.api-us1.com',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description:
            'Provide your full API url. It can be found in your account on the My Settings page under the "Developer" tab. Generally, the URL will be in the form https://<your-account>.api-us1.com. The API is accessed using a base URL that is specific to your account.',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
        {
          id: 'api_key',
          label: 'API Key',
          value:
            'a1ffa05a296f99780689a6ebd44b7c966e5591ee13cd38e5116c26e22104ac1bfaa9e00a',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: true,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: ['opportunities', 'pipelines'],
      settings_required_for_authorization: [],
      state: 'authorized',
      integration_state: 'configured',
      enabled: false,
      settings: {
        base_url: 'https://apideck1600217394.api-us1.com',
      },
      metadata: {},
      created_at: 1644833581713,
      updated_at: 1644843438490,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'file-storage+box',
      name: 'Box',
      tag_line:
        'Box empowers your teams by making it easy to work with people inside and outside your organization, protect your valuable content, and connect all your apps.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1632097547/icons/box.jpg',
      website: 'https://www.box.com/',
      unified_api: 'file-storage',
      service_id: 'box',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/box/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiZmlsZS1zdG9yYWdlIiwic2VydmljZV9pZCI6ImJveCIsImFwcGxpY2F0aW9uX2lkIjoiY2ZhWnJPUmdhSDJQTVFwSWNqVHBmaEVSSXBJRVVKSGV2MDl1Y2pUcCIsImlhdCI6MTY0NDkxNTA2MSwiZXhwIjoxNjQ1MDAxNDYxfQ.zQ9HFmHQJmA51Q52SjYQED4tZJDCRH3m2lqeWk1IdtI',
      revoke_url: null,
    },
    {
      id: 'crm+close',
      name: 'Close',
      tag_line:
        'Close is the inside sales CRM of choice for startups and SMBs. Make more calls, send more emails and close more deals starting today.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1531304652/catalog/closeio/icon128x128.png',
      logo: 'https://close.com/static/img/close-logo-dark.svg?h=0bedac01',
      website: 'https://close.com',
      unified_api: 'crm',
      service_id: 'close',
      auth_type: 'apiKey',
      custom_mappings: [],
      form_fields: [
        {
          id: 'api_key',
          label: 'API Key',
          value: 'xxdWtlJbxbHSGkUJFuknM6g5tsMb1r8lbFXOXOBXmG0iz',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: true,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'callable',
      integration_state: 'configured',
      enabled: true,
      settings: {},
      metadata: {},
      created_at: 1644843444995,
      updated_at: 1644843450309,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'lead+close',
      name: 'Close',
      tag_line:
        'Close is the inside sales CRM of choice for startups and SMBs. Make more calls, send more emails and close more deals starting today.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1531304652/catalog/closeio/icon128x128.png',
      logo: 'https://close.com/static/img/close-logo-dark.svg?h=0bedac01',
      website: 'https://close.com',
      unified_api: 'lead',
      service_id: 'close',
      auth_type: 'apiKey',
      custom_mappings: [],
      form_fields: [
        {
          id: 'api_key',
          label: 'API Key',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: true,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'lead+copper',
      name: 'Copper',
      tag_line:
        'When you need CRM software that works with G Suite, you need Copper. Give us a try and see how we can help your business build stronger customer relationships.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1535538972/catalog/copper/icon128x128.png',
      logo: 'https://www.cloudbakers.com/hs-fs/hubfs/Copper_Logo_L_fullcolor_onwhite.png?width=862&name=Copper_Logo_L_fullcolor_onwhite.png',
      website: 'https://www.copper.com/',
      unified_api: 'lead',
      service_id: 'copper',
      auth_type: 'apiKey',
      custom_mappings: [],
      form_fields: [
        {
          id: 'email',
          label: 'Email',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
        {
          id: 'api_key',
          label: 'API Key',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: true,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: ['opportunities'],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'crm+copper',
      name: 'Copper',
      tag_line:
        'When you need CRM software that works with G Suite, you need Copper. Give us a try and see how we can help your business build stronger customer relationships.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1535538972/catalog/copper/icon128x128.png',
      logo: 'https://www.cloudbakers.com/hs-fs/hubfs/Copper_Logo_L_fullcolor_onwhite.png?width=862&name=Copper_Logo_L_fullcolor_onwhite.png',
      website: 'https://www.copper.com/',
      unified_api: 'crm',
      service_id: 'copper',
      auth_type: 'apiKey',
      custom_mappings: [],
      form_fields: [
        {
          id: 'email',
          label: 'Email',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
        {
          id: 'api_key',
          label: 'API Key',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: true,
        },
      ],
      configurable_resources: ['opportunities'],
      resource_schema_support: [],
      resource_settings_support: ['opportunities'],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'script+crisp',
      name: 'Crisp',
      tag_line:
        "Discover our Customer Messaging Platform for Startups & SMB's. The one stop for sales, marketing & support in one software : Crisp. 14 Days free trial. No credit-card required. Try now ! We provide Knowledge base, Team Inbox, Chatbot, CRM and multiple other features to let you build your own way to customer success.",
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1531304704/catalog/crisp/icon128x128.png',
      logo: 'https://app.apideck.com/static/media/crisp-logo.1b35d0c4.png',
      website: 'https://crisp.chat',
      unified_api: 'script',
      service_id: 'crisp',
      auth_type: 'none',
      custom_mappings: [],
      form_fields: [
        {
          id: 'id',
          label: 'Id',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'file-storage+dropbox',
      name: 'Dropbox',
      tag_line:
        'Dropbox is a modern workspace designed to reduce busywork-so you can focus on the things that matter. Sign in and put your creative energy to work.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529455993/catalog/dropbox/icon128x128.png',
      website: 'https://www.dropbox.com/',
      unified_api: 'file-storage',
      service_id: 'dropbox',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/dropbox/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiZmlsZS1zdG9yYWdlIiwic2VydmljZV9pZCI6ImRyb3Bib3giLCJhcHBsaWNhdGlvbl9pZCI6ImNmYVpyT1JnYUgyUE1RcEljalRwZmhFUklwSUVVSkhldjA5dWNqVHAiLCJpYXQiOjE2NDQ5MTUwNjEsImV4cCI6MTY0NTAwMTQ2MX0.3vEN9C-Cw9z-Lxqgl1IVRWTlWlboIOMhSpWOMrioVr0',
      revoke_url: null,
    },
    {
      id: 'accounting+exact-online',
      name: 'Exact Online',
      tag_line:
        "Exact Cloud business software offers accounting and industry software in the cloud for SME's on desktop, laptop, tablet and mobile apps.",
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1548122132/catalog/exact-online/icon128x128.png',
      website: 'https://www.exact.com/',
      unified_api: 'accounting',
      service_id: 'exact-online',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/exact-online/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiYWNjb3VudGluZyIsInNlcnZpY2VfaWQiOiJleGFjdC1vbmxpbmUiLCJhcHBsaWNhdGlvbl9pZCI6ImNmYVpyT1JnYUgyUE1RcEljalRwZmhFUklwSUVVSkhldjA5dWNqVHAiLCJpYXQiOjE2NDQ5MTUwNjEsImV4cCI6MTY0NTAwMTQ2MX0.axKn2zpVT9TPbx8IhRV3Rvqyfxixe_zns3ZICn1-fm4',
      revoke_url: null,
    },
    {
      id: 'lead+freshsales',
      name: 'Freshsales',
      tag_line:
        'Freshsales is an online, cloud-based CRM with Integrated phone and email, User behavior tracking, Lead scoring and more.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1531304992/catalog/freshsales/icon128x128.png',
      website: 'https://www.freshworks.com/freshsales-crm/',
      unified_api: 'lead',
      service_id: 'freshsales',
      auth_type: 'apiKey',
      custom_mappings: [],
      form_fields: [
        {
          id: 'domain',
          label: 'Domain',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
        {
          id: 'api_key',
          label: 'API Key',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: true,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'script+google-analytics',
      name: 'Google Analytics',
      tag_line:
        'Google Analytics lets you measure your advertising ROI as well as track your Flash, video, and social networking sites and applications.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1531055926/catalog/google-analytics/icon128x128.png',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/d/df/Googleanalyticsicon.png',
      website: 'https://www.google.com/analytics/',
      unified_api: 'script',
      service_id: 'google-analytics',
      auth_type: 'none',
      custom_mappings: [],
      form_fields: [
        {
          id: 'id',
          label: 'Id',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'file-storage+google-drive',
      name: 'Google Drive',
      tag_line:
        "Google Drive is Google's file sync app that lets you store all of your files online alongside your Google Docs documents, and keep them synced with all of your devices.",
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529455952/catalog/google-drive/icon128x128.png',
      website: 'https://www.google.com/drive/index.html',
      unified_api: 'file-storage',
      service_id: 'google-drive',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/google-drive/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiZmlsZS1zdG9yYWdlIiwic2VydmljZV9pZCI6Imdvb2dsZS1kcml2ZSIsImFwcGxpY2F0aW9uX2lkIjoiY2ZhWnJPUmdhSDJQTVFwSWNqVHBmaEVSSXBJRVVKSGV2MDl1Y2pUcCIsImlhdCI6MTY0NDkxNTA2MSwiZXhwIjoxNjQ1MDAxNDYxfQ.g8NJ1jY7Rq4yjRY7DKY6UQPA-KaiRnm7vnh10mZlFFw',
      revoke_url: null,
    },
    {
      id: 'script+google-tag-manager',
      name: 'Google Tag Manager',
      tag_line:
        'Google Tag Manager is a free tool that allows you manage and deploy marketing tags (snippets of code or tracking pixels) on your website (or mobile app) without having to modify the code.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1537439207/catalog/google-tag-manager/icon128x128.svg',
      logo: 'https://app.apideck.com/static/media/google-tag-manager.c7c2b0cd.png',
      website: 'https://marketingplatform.google.com/about/tag-manager/',
      unified_api: 'script',
      service_id: 'google-tag-manager',
      auth_type: 'none',
      custom_mappings: [],
      form_fields: [
        {
          id: 'id',
          label: 'Id',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'crm+hubspot',
      name: 'HubSpot',
      tag_line:
        'HubSpot is your all-in-one stop for all of your marketing software needs.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529455982/catalog/hubspot/icon128x128.png',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/7/71/HubSpot_Logo.png',
      website: 'https://www.hubspot.com/',
      unified_api: 'crm',
      service_id: 'hubspot',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [],
      configurable_resources: ['opportunities'],
      resource_schema_support: [],
      resource_settings_support: ['opportunities'],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/hubspot/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiY3JtIiwic2VydmljZV9pZCI6Imh1YnNwb3QiLCJhcHBsaWNhdGlvbl9pZCI6ImNmYVpyT1JnYUgyUE1RcEljalRwZmhFUklwSUVVSkhldjA5dWNqVHAiLCJpYXQiOjE2NDQ5MTUwNjEsImV4cCI6MTY0NTAwMTQ2MX0.Wt4mvTNvUWXq4VmuPB3-_G28RZ-TCOo4_ju4NekaGV8',
      revoke_url: null,
    },
    {
      id: 'script+hubspot',
      name: 'HubSpot',
      tag_line:
        'HubSpot is your all-in-one stop for all of your marketing software needs.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529455982/catalog/hubspot/icon128x128.png',
      logo: 'https://upload.wikimedia.org/wikipedia/commons/7/71/HubSpot_Logo.png',
      website: 'https://www.hubspot.com/',
      unified_api: 'script',
      service_id: 'hubspot',
      auth_type: 'none',
      custom_mappings: [],
      form_fields: [
        {
          id: 'portal_id',
          label: 'Portal id',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: ['opportunities'],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'script+intercom',
      name: 'Intercom',
      tag_line:
        'We make customer messaging apps for sales, marketing, and support, connected on one platform. Our mission is to make business personal again.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529456145/catalog/intercom/icon128x128.png',
      logo: 'https://res.cloudinary.com/apideck/image/upload/v1554113418/catalog/intercom/logo.png',
      website: 'https://www.intercom.com/',
      unified_api: 'script',
      service_id: 'intercom',
      auth_type: 'none',
      custom_mappings: [],
      form_fields: [
        {
          id: 'app_id',
          label: 'App id',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'script+iubenda',
      name: 'Iubenda',
      tag_line:
        'Privacy & Cookie Policy Generator - for Websites and Apps. A 360° solution to make your sites and apps compliant with the law A complete set of solutions to make your website or app compliant with the law, across multiple languages and legislations',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1537374494/catalog/iubenda/icon128x128.png',
      logo: 'https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_a00b4cb22c823e513a77cc103e967d08/iubenda.png',
      website: 'https://www.iubenda.com/',
      unified_api: 'script',
      service_id: 'iubenda',
      auth_type: 'none',
      custom_mappings: [],
      form_fields: [
        {
          id: 'site_id',
          label: 'Site id',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
        {
          id: 'cookie_policy_id',
          label: 'Cookie policy id',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
        {
          id: 'id',
          label: 'Id',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'script+livechat',
      name: 'Livechat',
      tag_line:
        'LiveChat - premium live chat software for business. Over 28 000 companies from 150 countries use LiveChat. Try now, chat for free!',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1531305321/catalog/livechat/icon128x128.png',
      logo: 'https://www.livechatinc.com/livechat-logo.svg',
      website: 'https://www.livechatinc.com/',
      unified_api: 'script',
      service_id: 'livechat',
      auth_type: 'none',
      custom_mappings: [],
      form_fields: [
        {
          id: 'id',
          label: 'Id',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'script+metomic-io',
      name: 'Metomic',
      tag_line:
        "Compliance shouldn't mean sacrificing usability. We provide a world-class privacy-by-design API to ethically manage your users' data.",
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1567075564/catalog/metomic-io/icon128x128.jpg',
      logo: 'https://metomic.io/wp-content/uploads/2019/04/metomic-logo-1.svg',
      website: 'https://metomic.io/',
      unified_api: 'script',
      service_id: 'metomic-io',
      auth_type: 'none',
      custom_mappings: [],
      form_fields: [
        {
          id: 'project_id',
          label: 'Project id',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
        {
          id: 'id',
          label: 'Id',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'crm+microsoft-dynamics',
      name: 'Microsoft Dynamics CRM',
      tag_line:
        'Dynamics CRM is a leading customer resource management and enterprise resource planning software.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1531056034/catalog/microsoft-dynamics/icon128x128.png',
      website: 'https://dynamics.microsoft.com/en-us/',
      unified_api: 'crm',
      service_id: 'microsoft-dynamics',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [
        {
          id: 'organisation_url',
          label: 'Organisation URL',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description:
            'The API is accessed using a URL that is specific to your organisation inside Microsoft Dynamics. Follow the guide to find out your organisation url https://migration.trujay.com/help/find-url-microsoft-dynamics-365/. Format: https://<:your_organization_url>/api/data/v9.0.',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: ['organisation_url'],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'lead+microsoft-dynamics',
      name: 'Microsoft Dynamics CRM',
      tag_line:
        'Dynamics CRM is a leading customer resource management and enterprise resource planning software.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1531056034/catalog/microsoft-dynamics/icon128x128.png',
      website: 'https://dynamics.microsoft.com/en-us/',
      unified_api: 'lead',
      service_id: 'microsoft-dynamics',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [
        {
          id: 'organisation_url',
          label: 'Organisation URL',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description:
            'The API is accessed using a URL that is specific to your organisation inside Microsoft Dynamics. Follow the guide to find out your organisation url https://migration.trujay.com/help/find-url-microsoft-dynamics-365/. Format: https://<:your_organization_url>/api/data/v9.0.',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: ['organisation_url'],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'accounting+myob',
      name: 'MYOB',
      tag_line:
        'Business software that sets you up for success. Try our online accounting solutions for tax, payroll, super and invoicing. Your 30-day free trial is waiting.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1554586086/catalog/myob/icon128x128.jpg',
      website: 'https://myob.com',
      unified_api: 'accounting',
      service_id: 'myob',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [
        {
          id: 'client_id',
          label: 'Client ID',
          value: '28bd505e-e97f-4ca1-97c2-c58658dfba35',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: true,
          sensitive: false,
        },
        {
          id: 'company_uri',
          label: 'Company File',
          value:
            'https://arl2.api.myob.com/accountright/c930d343-5dfa-4de6-bd4a-49f9a9d2d206',
          placeholder: 'Select a Company File',
          mask: false,
          type: 'select',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
          options: [
            {
              value:
                'https://arl2.api.myob.com/accountright/c930d343-5dfa-4de6-bd4a-49f9a9d2d206',
              label: 'Apideck',
            },
          ],
          allow_custom_values: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'callable',
      enabled: true,
      settings: {
        company_uri:
          'https://arl2.api.myob.com/accountright/c930d343-5dfa-4de6-bd4a-49f9a9d2d206',
        client_id: '28bd505e-e97f-4ca1-97c2-c58658dfba35',
      },
      metadata: {},
      created_at: 1644835221486,
      updated_at: 1644849223384,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/myob/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiYWNjb3VudGluZyIsInNlcnZpY2VfaWQiOiJteW9iIiwiYXBwbGljYXRpb25faWQiOiJjZmFack9SZ2FIMlBNUXBJY2pUcGZoRVJJcElFVUpIZXYwOXVjalRwIiwiaWF0IjoxNjQ0OTE1MDYxLCJleHAiOjE2NDUwMDE0NjF9.VBXYTw4ux6-U3fQx4Ql7-JH07NDIg7KC-9qLAcvLBDU',
      revoke_url:
        'https://unify.apideck.com/vault/revoke/myob/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiYWNjb3VudGluZyIsInNlcnZpY2VfaWQiOiJteW9iIiwiYXBwbGljYXRpb25faWQiOiJjZmFack9SZ2FIMlBNUXBJY2pUcGZoRVJJcElFVUpIZXYwOXVjalRwIiwiaWF0IjoxNjQ0OTE1MDYxLCJleHAiOjE2NDUwMDE0NjF9.VBXYTw4ux6-U3fQx4Ql7-JH07NDIg7KC-9qLAcvLBDU',
    },
    {
      id: 'file-storage+onedrive',
      name: 'OneDrive',
      tag_line:
        'Get 5 GB of free OneDrive cloud storage! Save your files and photos to OneDrive and access them from any device, anywhere',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1531305571/catalog/onedrive/icon128x128.png',
      website: 'https://onedrive.live.com',
      unified_api: 'file-storage',
      service_id: 'onedrive',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [
        {
          id: 'drive_id',
          label: 'Drive',
          value: '',
          placeholder: 'Select a Drive',
          mask: false,
          type: 'select',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
          options: [],
          allow_custom_values: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/onedrive/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiZmlsZS1zdG9yYWdlIiwic2VydmljZV9pZCI6Im9uZWRyaXZlIiwiYXBwbGljYXRpb25faWQiOiJjZmFack9SZ2FIMlBNUXBJY2pUcGZoRVJJcElFVUpIZXYwOXVjalRwIiwiaWF0IjoxNjQ0OTE1MDY0LCJleHAiOjE2NDUwMDE0NjR9.egPuPogR2aM0mCNUyKOAMvCtFxBH_oOV5_VuyUOmZW4',
      revoke_url: null,
    },
    {
      id: 'lead+pipedrive',
      name: 'Pipedrive',
      tag_line:
        'Pipedrive is the easy-to-use, #1 user-rated CRM tool. Get more qualified leads and grow your business. Sign up for a 14-day free trial.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529455988/catalog/pipedrive/icon128x128.png',
      logo: 'https://res.cloudinary.com/apideck/image/upload/v1591366328/catalog/pipedrive/Pipedrive_full_logo_dark.png',
      website: 'https://www.pipedrive.com/',
      unified_api: 'lead',
      service_id: 'pipedrive',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'added',
      enabled: true,
      settings: {},
      metadata: {},
      created_at: 1644849382120,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/pipedrive/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoibGVhZCIsInNlcnZpY2VfaWQiOiJwaXBlZHJpdmUiLCJhcHBsaWNhdGlvbl9pZCI6ImNmYVpyT1JnYUgyUE1RcEljalRwZmhFUklwSUVVSkhldjA5dWNqVHAiLCJpYXQiOjE2NDQ5MTUwNjQsImV4cCI6MTY0NTAwMTQ2NH0.Mfa69jxpvPyjugV5kgt7giA5F1xnbdfy6Y5F6dP1yOE',
      revoke_url: null,
    },
    {
      id: 'crm+pipedrive',
      name: 'Pipedrive',
      tag_line:
        'Pipedrive is the easy-to-use, #1 user-rated CRM tool. Get more qualified leads and grow your business. Sign up for a 14-day free trial.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529455988/catalog/pipedrive/icon128x128.png',
      logo: 'https://res.cloudinary.com/apideck/image/upload/v1591366328/catalog/pipedrive/Pipedrive_full_logo_dark.png',
      website: 'https://www.pipedrive.com/',
      unified_api: 'crm',
      service_id: 'pipedrive',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'callable',
      enabled: true,
      settings: {},
      metadata: {
        accountInfo: {
          lookupId: '5642511',
        },
      },
      created_at: 1644834314961,
      updated_at: 1644849367837,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/pipedrive/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiY3JtIiwic2VydmljZV9pZCI6InBpcGVkcml2ZSIsImFwcGxpY2F0aW9uX2lkIjoiY2ZhWnJPUmdhSDJQTVFwSWNqVHBmaEVSSXBJRVVKSGV2MDl1Y2pUcCIsImlhdCI6MTY0NDkxNTA2NCwiZXhwIjoxNjQ1MDAxNDY0fQ.tBaiF_s6sTD6OQ4uXFfqEVBYM2ImzD14T9Wbq4Y2nNk',
      revoke_url:
        'https://unify.apideck.com/vault/revoke/pipedrive/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiY3JtIiwic2VydmljZV9pZCI6InBpcGVkcml2ZSIsImFwcGxpY2F0aW9uX2lkIjoiY2ZhWnJPUmdhSDJQTVFwSWNqVHBmaEVSSXBJRVVKSGV2MDl1Y2pUcCIsImlhdCI6MTY0NDkxNTA2NCwiZXhwIjoxNjQ1MDAxNDY0fQ.tBaiF_s6sTD6OQ4uXFfqEVBYM2ImzD14T9Wbq4Y2nNk',
    },
    {
      id: 'sms+plivo',
      name: 'Plivo',
      tag_line:
        'Plivo is an easy-to-use tool that lets you send & receive SMS and voice calls.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1531305712/catalog/plivo/icon128x128.png',
      logo: 'https://www.twilio.com/docs/static/company/img/logos/red/twilio-logo-red.3db67e8d6.png',
      website: 'https://www.plivo.com/',
      unified_api: 'sms',
      service_id: 'plivo',
      auth_type: 'basic',
      custom_mappings: [],
      form_fields: [
        {
          id: 'auth_id',
          label: 'Auth Id',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
        {
          id: 'auth_token',
          label: 'Auth token',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'accounting+quickbooks',
      name: 'QuickBooks',
      tag_line:
        'QuickBooks is an accounting software package developed and marketed by Intuit. QuickBooks products are geared mainly toward small and medium-sized businesses and offer on-premises accounting applications as well as cloud-based versions that accept business payments, manage and pay bills, and payroll functions.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529456366/catalog/quickbooks/icon128x128.png',
      website: 'https://quickbooks.intuit.com/',
      unified_api: 'accounting',
      service_id: 'quickbooks',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [
        {
          id: 'realm_id',
          label: 'Company ID',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: true,
          sensitive: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/quickbooks/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiYWNjb3VudGluZyIsInNlcnZpY2VfaWQiOiJxdWlja2Jvb2tzIiwiYXBwbGljYXRpb25faWQiOiJjZmFack9SZ2FIMlBNUXBJY2pUcGZoRVJJcElFVUpIZXYwOXVjalRwIiwiaWF0IjoxNjQ0OTE1MDY0LCJleHAiOjE2NDUwMDE0NjR9.p_28FC3af_xWUTnem3mpdrbJaFeBbH8E2Y5ig1IA59I',
      revoke_url: null,
    },
    {
      id: 'ats+sage-hr',
      name: 'Sage HR',
      tag_line:
        'An award-winning HR technology company that provides attendance, performance & recruitment management for customers worldwide. Free 14-day trial! Easy Setup! Cancel any time!',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1634905030/icons/sage-hr.jpg',
      website: 'https://sage.hr/',
      unified_api: 'ats',
      service_id: 'sage-hr',
      auth_type: 'apiKey',
      custom_mappings: [],
      form_fields: [
        {
          id: 'base_url',
          label: 'Base url',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
        {
          id: 'api_key',
          label: 'API Key',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: true,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'lead+salesflare',
      name: 'Salesflare',
      tag_line:
        'The #1 simple CRM for small businesses selling B2B. Integrate with Google & Outlook. Be fully mobile. Automate your CRM from existing data.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1531305954/catalog/salesflare/icon128x128.png',
      logo: 'https://salesflare.com/img/nav-logo.png',
      website: 'https://salesflare.com',
      unified_api: 'lead',
      service_id: 'salesflare',
      auth_type: 'apiKey',
      custom_mappings: [],
      form_fields: [
        {
          id: 'api_key',
          label: 'API Key',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: true,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: ['opportunities'],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'crm+salesflare',
      name: 'Salesflare',
      tag_line:
        'The #1 simple CRM for small businesses selling B2B. Integrate with Google & Outlook. Be fully mobile. Automate your CRM from existing data.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1531305954/catalog/salesflare/icon128x128.png',
      logo: 'https://salesflare.com/img/nav-logo.png',
      website: 'https://salesflare.com',
      unified_api: 'crm',
      service_id: 'salesflare',
      auth_type: 'apiKey',
      custom_mappings: [],
      form_fields: [
        {
          id: 'api_key',
          label: 'API Key',
          value: 'xxdWtlJbxbHSGkUJFuknM6g5tsMb1r8lbFXOXOBXmG0iz',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description: '',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: true,
        },
      ],
      configurable_resources: ['opportunities'],
      resource_schema_support: [],
      resource_settings_support: ['opportunities'],
      settings_required_for_authorization: [],
      state: 'callable',
      enabled: true,
      settings: {},
      metadata: {},
      created_at: 1644843460470,
      updated_at: 1644843466402,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'lead+salesforce',
      name: 'Salesforce',
      tag_line:
        'CRM software solutions and enterprise cloud computing from Salesforce, the leader in customer relationship management (CRM) and PaaS. Free 30 day trial.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529456047/catalog/salesforce/icon128x128.png',
      logo: 'https://c1.sfdcstatic.com/content/dam/web/en_us/www/images/home/logo-salesforce-m.svg',
      website: 'https://www.salesforce.com',
      unified_api: 'lead',
      service_id: 'salesforce',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [
        {
          id: 'instance_url',
          label: 'Instance url',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
      ],
      configurable_resources: ['leads'],
      resource_schema_support: ['leads'],
      resource_settings_support: ['opportunities'],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/salesforce/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoibGVhZCIsInNlcnZpY2VfaWQiOiJzYWxlc2ZvcmNlIiwiYXBwbGljYXRpb25faWQiOiJjZmFack9SZ2FIMlBNUXBJY2pUcGZoRVJJcElFVUpIZXYwOXVjalRwIiwiaWF0IjoxNjQ0OTE1MDY0LCJleHAiOjE2NDUwMDE0NjR9.2--sWXz_yOVTYtTiZYtc72LdsU4wKyq_Z8FE_D_TaTw',
      revoke_url: null,
    },
    {
      id: 'crm+salesforce',
      name: 'Salesforce',
      tag_line:
        'CRM software solutions and enterprise cloud computing from Salesforce, the leader in customer relationship management (CRM) and PaaS. Free 30 day trial.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529456047/catalog/salesforce/icon128x128.png',
      logo: 'https://c1.sfdcstatic.com/content/dam/web/en_us/www/images/home/logo-salesforce-m.svg',
      website: 'https://www.salesforce.com',
      unified_api: 'crm',
      service_id: 'salesforce',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [
        {
          id: 'instance_url',
          label: 'Instance url',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
      ],
      configurable_resources: [
        'leads',
        'contacts',
        'companies',
        'opportunities',
        'activities',
      ],
      resource_schema_support: [
        'opportunities',
        'companies',
        'contacts',
        'leads',
        'activities',
      ],
      resource_settings_support: ['opportunities'],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/salesforce/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiY3JtIiwic2VydmljZV9pZCI6InNhbGVzZm9yY2UiLCJhcHBsaWNhdGlvbl9pZCI6ImNmYVpyT1JnYUgyUE1RcEljalRwZmhFUklwSUVVSkhldjA5dWNqVHAiLCJpYXQiOjE2NDQ5MTUwNjQsImV4cCI6MTY0NTAwMTQ2NH0.POAk0ewqor4IZc_YEIb1BxscsQZDCm7cNuZiWVixof4',
      revoke_url: null,
    },
    {
      id: 'file-storage+sharepoint',
      name: 'SharePoint',
      tag_line:
        'SharePoint is business collaboration software that helps simplify content management, search, business intelligence. It also has a strong component around sharing for intranet and internet sites.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1531056154/catalog/sharepoint/icon128x128.png',
      website: 'https://products.office.com',
      unified_api: 'file-storage',
      service_id: 'sharepoint',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [
        {
          id: 'site_id',
          label: 'SharePoint Site',
          value: '',
          placeholder: 'Select a Site',
          mask: false,
          type: 'select',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
          options: [],
          allow_custom_values: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/sharepoint/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiZmlsZS1zdG9yYWdlIiwic2VydmljZV9pZCI6InNoYXJlcG9pbnQiLCJhcHBsaWNhdGlvbl9pZCI6ImNmYVpyT1JnYUgyUE1RcEljalRwZmhFUklwSUVVSkhldjA5dWNqVHAiLCJpYXQiOjE2NDQ5MTUwNjQsImV4cCI6MTY0NTAwMTQ2NH0.7ujzmrzYv20kdq-yv1vCK-CJRaCaZvP7eJ33pq9y-cM',
      revoke_url: null,
    },
    {
      id: 'ecommerce+shopify',
      name: 'Shopify',
      tag_line:
        'Sell anywhere, to anyone, with Shopify’s ecommerce platform and point of sale features.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529456131/catalog/shopify/icon128x128.png',
      website: 'https://www.shopify.com/',
      unified_api: 'ecommerce',
      service_id: 'shopify',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [
        {
          id: 'shop',
          label: 'Shop',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          description:
            'Your shop name is usually the first part of your domain (for example - https://{shop}.myshopify.com)',
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: ['shop'],
      state: 'added',
      enabled: true,
      settings: {},
      metadata: {},
      created_at: 1644832992688,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'lead+slack',
      name: 'Slack',
      tag_line:
        "Slack is where work flows. It's where the people you need, the information you share, and the tools you use come together to get things done.",
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529455910/catalog/slack/icon128x128.png',
      logo: 'https://a.slack-edge.com/80588/marketing/img/icons/icon_slack_hash_colored.png',
      website: 'https://slack.com/',
      unified_api: 'lead',
      service_id: 'slack',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [
        {
          id: 'channel',
          label: 'Channel',
          value: '',
          placeholder: 'Select a channel',
          mask: false,
          type: 'select',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
          options: [],
          allow_custom_values: true,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/slack/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoibGVhZCIsInNlcnZpY2VfaWQiOiJzbGFjayIsImFwcGxpY2F0aW9uX2lkIjoiY2ZhWnJPUmdhSDJQTVFwSWNqVHBmaEVSSXBJRVVKSGV2MDl1Y2pUcCIsImlhdCI6MTY0NDkxNTA2NCwiZXhwIjoxNjQ1MDAxNDY0fQ.HkECD2zT92Yy_vh6-D4JZGz8dbfFdTjYrD59nxka6kw',
      revoke_url: null,
    },
    {
      id: 'lead+teamleader',
      name: 'Teamleader',
      tag_line:
        'Faced with a mountain of administration? Don’t panic. We’ll guide you over.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1536884849/catalog/teamleader/icon128x128.jpg',
      logo: 'https://www.drupal.org/files/TL_logo_default_rgb.png',
      website: 'https://www.teamleader.eu/',
      unified_api: 'lead',
      service_id: 'teamleader',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/teamleader/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoibGVhZCIsInNlcnZpY2VfaWQiOiJ0ZWFtbGVhZGVyIiwiYXBwbGljYXRpb25faWQiOiJjZmFack9SZ2FIMlBNUXBJY2pUcGZoRVJJcElFVUpIZXYwOXVjalRwIiwiaWF0IjoxNjQ0OTE1MDY0LCJleHAiOjE2NDUwMDE0NjR9.FF20Xrbjcd_uEE8nTK9ji5JEHNJF31n9lUOr9KnFckg',
      revoke_url: null,
    },
    {
      id: 'crm+teamleader',
      name: 'Teamleader',
      tag_line:
        'Faced with a mountain of administration? Don’t panic. We’ll guide you over.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1536884849/catalog/teamleader/icon128x128.jpg',
      logo: 'https://www.drupal.org/files/TL_logo_default_rgb.png',
      website: 'https://www.teamleader.eu/',
      unified_api: 'crm',
      service_id: 'teamleader',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/teamleader/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiY3JtIiwic2VydmljZV9pZCI6InRlYW1sZWFkZXIiLCJhcHBsaWNhdGlvbl9pZCI6ImNmYVpyT1JnYUgyUE1RcEljalRwZmhFUklwSUVVSkhldjA5dWNqVHAiLCJpYXQiOjE2NDQ5MTUwNjQsImV4cCI6MTY0NTAwMTQ2NH0.PUk7kIUG6Nz0Gy_ScWLyZOn4IEj-jpy6SpyFFUNRjMU',
      revoke_url: null,
    },
    {
      id: 'sms+twilio',
      name: 'Twilio',
      tag_line:
        'Cloud communications platform for building SMS, Voice & Messaging applications on an API built for global scale. Get started with a free trial.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529456121/catalog/twilio/icon128x128.png',
      logo: 'https://www.twilio.com/docs/static/company/img/logos/red/twilio-logo-red.3db67e8d6.png',
      website: 'https://www.twilio.com/',
      unified_api: 'sms',
      service_id: 'twilio',
      auth_type: 'basic',
      custom_mappings: [],
      form_fields: [
        {
          id: 'account_sid',
          label: 'Account sid',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
        {
          id: 'auth_token',
          label: 'Auth token',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url: null,
      revoke_url: null,
    },
    {
      id: 'accounting+xero',
      name: 'Xero',
      tag_line:
        'Get paid sooner when you accept payments online straight from a Xero invoice. Give your customers different payment options, including PayPal and Stripe.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529456372/catalog/xero/icon128x128.png',
      website: 'https://www.xero.com',
      unified_api: 'accounting',
      service_id: 'xero',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [
        {
          id: 'tenant_id',
          label: 'Tenants',
          value: '',
          placeholder: 'Select a Tenant',
          mask: false,
          type: 'select',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: false,
          sensitive: false,
          options: [],
          allow_custom_values: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/xero/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiYWNjb3VudGluZyIsInNlcnZpY2VfaWQiOiJ4ZXJvIiwiYXBwbGljYXRpb25faWQiOiJjZmFack9SZ2FIMlBNUXBJY2pUcGZoRVJJcElFVUpIZXYwOXVjalRwIiwiaWF0IjoxNjQ0OTE1MDY0LCJleHAiOjE2NDUwMDE0NjR9.8wAs7xbVjE2Ud24a7sOfTliugAm0E_gCzU3M_ov1S_s',
      revoke_url: null,
    },
    {
      id: 'crm+zendesk-sell',
      name: 'Zendesk Sell',
      tag_line:
        'Zendesk Sell (formerly Base) is a sales automation tool to enhance productivity, processes, and pipeline visibility for sales teams.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1551284663/catalog/zendesk-sell/icon128x128.png',
      website: 'https://www.zendesk.com/sell/',
      unified_api: 'crm',
      service_id: 'zendesk-sell',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [],
      configurable_resources: ['contacts'],
      resource_schema_support: [],
      resource_settings_support: ['contacts'],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/zendesk-sell/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoiY3JtIiwic2VydmljZV9pZCI6InplbmRlc2stc2VsbCIsImFwcGxpY2F0aW9uX2lkIjoiY2ZhWnJPUmdhSDJQTVFwSWNqVHBmaEVSSXBJRVVKSGV2MDl1Y2pUcCIsImlhdCI6MTY0NDkxNTA2NCwiZXhwIjoxNjQ1MDAxNDY0fQ.F9JxJWL5OvuLayJmflo1niSSaCaiC7xzMmUEJeR_ZZw',
      revoke_url: null,
    },
    {
      id: 'lead+zendesk-sell',
      name: 'Zendesk Sell',
      tag_line:
        'Zendesk Sell (formerly Base) is a sales automation tool to enhance productivity, processes, and pipeline visibility for sales teams.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1551284663/catalog/zendesk-sell/icon128x128.png',
      website: 'https://www.zendesk.com/sell/',
      unified_api: 'lead',
      service_id: 'zendesk-sell',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: ['contacts'],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/zendesk-sell/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoibGVhZCIsInNlcnZpY2VfaWQiOiJ6ZW5kZXNrLXNlbGwiLCJhcHBsaWNhdGlvbl9pZCI6ImNmYVpyT1JnYUgyUE1RcEljalRwZmhFUklwSUVVSkhldjA5dWNqVHAiLCJpYXQiOjE2NDQ5MTUwNjQsImV4cCI6MTY0NTAwMTQ2NH0.700pCHYkMSd17InNdg3GQSEYOunF6BFnZF0loMEJw08',
      revoke_url: null,
    },
    {
      id: 'lead+zoho-crm',
      name: 'Zoho CRM',
      tag_line:
        'Zoho makes it easy to get the complete picture of your sales cycle and stay on top of your business opportunities. Never lose another lead again.',
      icon: 'https://res.cloudinary.com/apideck/image/upload/v1529456151/catalog/zoho-crm/icon128x128.png',
      website: 'https://www.zoho.com/crm/',
      unified_api: 'lead',
      service_id: 'zoho-crm',
      auth_type: 'oauth2',
      custom_mappings: [],
      form_fields: [
        {
          id: 'api_domain',
          label: 'API Domain',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: true,
          sensitive: false,
        },
        {
          id: 'accounts_server',
          label: 'Accounts Server',
          value: '',
          placeholder: '',
          mask: false,
          type: 'text',
          required: true,
          disabled: false,
          custom_field: false,
          hidden: true,
          sensitive: false,
        },
      ],
      configurable_resources: [],
      resource_schema_support: [],
      resource_settings_support: [],
      settings_required_for_authorization: [],
      state: 'available',
      integration_state: 'configured',
      enabled: false,
      authorize_url:
        'https://unify.apideck.com/vault/authorize/zoho-crm/cfaZrORgaH2PMQpIcjTpfhERIpIEUJHev09ucjTp?state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdW1lcl9pZCI6InRlc3QtY29uc3VtZXItMTIzNCIsInVuaWZpZWRfYXBpIjoibGVhZCIsInNlcnZpY2VfaWQiOiJ6b2hvLWNybSIsImFwcGxpY2F0aW9uX2lkIjoiY2ZhWnJPUmdhSDJQTVFwSWNqVHBmaEVSSXBJRVVKSGV2MDl1Y2pUcCIsImlhdCI6MTY0NDkxNTA2NCwiZXhwIjoxNjQ1MDAxNDY0fQ.7wxXdb8IGEwe5wO6hLSuEHZ8rEkAJjhRTe-WAcQoDVc',
      revoke_url: null,
    },
  ],
};
